# Generated by Django 5.2.7 on 2025-10-18 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
        ('servicio_adicional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('id_servicio_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_adicional.servicio_adicional')),
            ],
        ),
    ]
